AWSTemplateFormatVersion: 2010-09-09
Description: |
  This cfn file is a static website application deployed on AWS Simple Storage Service (S3), served through Cloudfront and Route 53 using AWS Cloudformation Service.

Parameters:

  KittensSubDomainName:
    Description: full domain name like kittens.hasansivri.com
    Type: String
    AllowedPattern: (?!-)[a-zA-Z0-9-.]{1,63}(?<!-)
  
Resources:

  HasanS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref KittensSubDomainName
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced
      PublicAccessBlockConfiguration:
        BlockPublicAcls: FALSE
      WebsiteConfiguration:
        IndexDocument: index.html

  HasanBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref HasanS3Bucket
      PolicyDocument:     
        Version: 2012-10-17
        Statement:
          - Action:
              - 's3:GetObject'
            Effect: Allow
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref HasanS3Bucket
                - /*
            Principal: '*'

  HasanCloudFront:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
        - !Ref KittensSubDomainName
        Comment: My First Cloudfront cfn
        DefaultCacheBehavior: 
          AllowedMethods: 
            - GET 
            - HEAD
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
          Compress: true
          TargetOriginId: hasancrf
          ViewerProtocolPolicy: allow-all
        DefaultRootObject: index.html
        Enabled: true
        HttpVersion: http2
        Origins: 
          - CustomOriginConfig: 
              OriginProtocolPolicy: http-only
            DomainName: !Select [2 , !Split ["/" , !GetAtt HasanS3Bucket.WebsiteURL]]
            Id: hasancrf
        PriceClass: PriceClass_All
        ViewerCertificate: 
          AcmCertificateArn: arn:aws:acm:us-east-1:877540899436:certificate/75717c7a-a517-439a-aa5a-1e5cd13e8dea
          MinimumProtocolVersion: TLSv1.2_2021
          SslSupportMethod: sni-only

  HasanRoute53:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: Z00796563AXW7EZRZB51Y
      RecordSets: 
        - AliasTarget: 
            DNSName: !GetAtt HasanCloudFront.DomainName
            HostedZoneId: Z2FDTNDATAQYW2
          Name: !Ref KittensSubDomainName
          Type: A
        
Outputs:
  BucketName: 
    Description: S3 Bucket URL for Kittens Website
    Value: !GetAtt HasanS3Bucket.WebsiteURL
  CloudfrontEndpoint:
    Description: Endpoint for Kittens Cloudfront
    Value: !GetAtt HasanCloudFront.DomainName
  FullDomainName:
    Description: Full Domain Name of my Application
    Value: !Ref KittensSubDomainName